<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="8" ignored="0" total="13" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="VisorTestSuite" duration-ms="134483" started-at="2019-06-25T23:31:10Z" finished-at="2019-06-25T23:33:24Z">
    <groups>
    </groups>
    <test name="MantenimientoCategoriaTest" duration-ms="134483" started-at="2019-06-25T23:31:10Z" finished-at="2019-06-25T23:33:24Z">
      <class name="pe.com.MDRO.test.system.selenium.testcase.MListaEtiqueta">
        <test-method status="FAIL" signature="editar_etiqueta_flujoBasico()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MListaEtiqueta@4e04a765]" name="editar_etiqueta_flujoBasico" duration-ms="10914" started-at="2019-06-25T23:32:52Z" finished-at="2019-06-25T23:33:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at pe.com.MDRO.test.system.selenium.testcase.MListaEtiqueta.editar_etiqueta_flujoBasico(MListaEtiqueta.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editar_etiqueta_flujoBasico -->
        <test-method status="FAIL" signature="eliminar_etiqueta_flujoBasico()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MListaEtiqueta@4e04a765]" name="eliminar_etiqueta_flujoBasico" duration-ms="6015" started-at="2019-06-25T23:33:03Z" finished-at="2019-06-25T23:33:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at pe.com.MDRO.test.system.selenium.testcase.MListaEtiqueta.eliminar_etiqueta_flujoBasico(MListaEtiqueta.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- eliminar_etiqueta_flujoBasico -->
      </class> <!-- pe.com.MDRO.test.system.selenium.testcase.MListaEtiqueta -->
      <class name="pe.com.MDRO.test.system.selenium.testcase.MantenimientoEtiqueta">
        <test-method status="PASS" signature="insertarEtiqueta_FlujoBasico()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoEtiqueta@3b81a1bc]" name="insertarEtiqueta_FlujoBasico" duration-ms="4796" started-at="2019-06-25T23:31:35Z" finished-at="2019-06-25T23:31:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertarEtiqueta_FlujoBasico -->
        <test-method status="FAIL" signature="insertarCategoria_FlujoAlternativo()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoEtiqueta@3b81a1bc]" name="insertarCategoria_FlujoAlternativo" duration-ms="2144" started-at="2019-06-25T23:31:40Z" depends-on-methods="pe.com.MDRO.test.system.selenium.testcase.MantenimientoEtiqueta.insertarEtiqueta_FlujoBasico" finished-at="2019-06-25T23:31:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Nombre: Error de validación: se necesita un valor.] but found [Nombre: Validation Error: Value is required.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Nombre: Error de validación: se necesita un valor.] but found [Nombre: Validation Error: Value is required.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pe.com.MDRO.test.system.selenium.testcase.MantenimientoEtiqueta.insertarCategoria_FlujoAlternativo(MantenimientoEtiqueta.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertarCategoria_FlujoAlternativo -->
      </class> <!-- pe.com.MDRO.test.system.selenium.testcase.MantenimientoEtiqueta -->
      <class name="pe.com.MDRO.test.system.selenium.testcase.MListaCategoria">
        <test-method status="PASS" signature="inicioClase()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MListaCategoria@13fee20c]" name="inicioClase" is-config="true" duration-ms="3509" started-at="2019-06-25T23:31:10Z" finished-at="2019-06-25T23:31:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inicioClase -->
        <test-method status="PASS" signature="inicioClase()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MListaEtiqueta@4e04a765]" name="inicioClase" is-config="true" duration-ms="2974" started-at="2019-06-25T23:31:13Z" finished-at="2019-06-25T23:31:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inicioClase -->
        <test-method status="PASS" signature="inicioClase()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MListaTiendaPage@783e6358]" name="inicioClase" is-config="true" duration-ms="2959" started-at="2019-06-25T23:31:16Z" finished-at="2019-06-25T23:31:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inicioClase -->
        <test-method status="PASS" signature="inicioClase()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoCategoria@5f2050f6]" name="inicioClase" is-config="true" duration-ms="2986" started-at="2019-06-25T23:31:19Z" finished-at="2019-06-25T23:31:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inicioClase -->
        <test-method status="PASS" signature="inicioClase()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoEtiqueta@3b81a1bc]" name="inicioClase" is-config="true" duration-ms="2936" started-at="2019-06-25T23:31:22Z" finished-at="2019-06-25T23:31:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inicioClase -->
        <test-method status="PASS" signature="inicioClase()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoTienda@64616ca2]" name="inicioClase" is-config="true" duration-ms="2938" started-at="2019-06-25T23:31:25Z" finished-at="2019-06-25T23:31:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inicioClase -->
        <test-method status="PASS" signature="editar_categoria_flujoBasico()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MListaCategoria@13fee20c]" name="editar_categoria_flujoBasico" duration-ms="7204" started-at="2019-06-25T23:32:15Z" finished-at="2019-06-25T23:32:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editar_categoria_flujoBasico -->
        <test-method status="FAIL" signature="eliminar_categoria_flujoBasico()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MListaCategoria@13fee20c]" name="eliminar_categoria_flujoBasico" duration-ms="30039" started-at="2019-06-25T23:32:22Z" finished-at="2019-06-25T23:32:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at pe.com.MDRO.test.system.selenium.testcase.MListaCategoria.eliminar_categoria_flujoBasico(MListaCategoria.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- eliminar_categoria_flujoBasico -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MListaCategoria@13fee20c]" name="tearDown" is-config="true" duration-ms="547" started-at="2019-06-25T23:33:21Z" finished-at="2019-06-25T23:33:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MListaEtiqueta@4e04a765]" name="tearDown" is-config="true" duration-ms="543" started-at="2019-06-25T23:33:22Z" finished-at="2019-06-25T23:33:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MListaTiendaPage@783e6358]" name="tearDown" is-config="true" duration-ms="543" started-at="2019-06-25T23:33:22Z" finished-at="2019-06-25T23:33:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoCategoria@5f2050f6]" name="tearDown" is-config="true" duration-ms="543" started-at="2019-06-25T23:33:23Z" finished-at="2019-06-25T23:33:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoEtiqueta@3b81a1bc]" name="tearDown" is-config="true" duration-ms="542" started-at="2019-06-25T23:33:23Z" finished-at="2019-06-25T23:33:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoTienda@64616ca2]" name="tearDown" is-config="true" duration-ms="544" started-at="2019-06-25T23:33:24Z" finished-at="2019-06-25T23:33:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- pe.com.MDRO.test.system.selenium.testcase.MListaCategoria -->
      <class name="pe.com.MDRO.test.system.selenium.testcase.MListaTiendaPage">
        <test-method status="FAIL" signature="editar_tienda_flujoBasico()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MListaTiendaPage@783e6358]" name="editar_tienda_flujoBasico" duration-ms="6016" started-at="2019-06-25T23:33:09Z" finished-at="2019-06-25T23:33:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at pe.com.MDRO.test.system.selenium.testcase.MListaTiendaPage.editar_tienda_flujoBasico(MListaTiendaPage.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editar_tienda_flujoBasico -->
        <test-method status="FAIL" signature="eliminar_tienda_flujoBasico()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MListaTiendaPage@783e6358]" name="eliminar_tienda_flujoBasico" duration-ms="6014" started-at="2019-06-25T23:33:15Z" finished-at="2019-06-25T23:33:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at pe.com.MDRO.test.system.selenium.testcase.MListaTiendaPage.eliminar_tienda_flujoBasico(MListaTiendaPage.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- eliminar_tienda_flujoBasico -->
      </class> <!-- pe.com.MDRO.test.system.selenium.testcase.MListaTiendaPage -->
      <class name="pe.com.MDRO.test.system.selenium.testcase.MantenimientoTienda">
        <test-method status="FAIL" signature="insertarTienda_FlujoBasico()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoTienda@64616ca2]" name="insertarTienda_FlujoBasico" duration-ms="32722" started-at="2019-06-25T23:31:42Z" finished-at="2019-06-25T23:32:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at pe.com.MDRO.test.system.selenium.testcase.MantenimientoTienda.insertarTienda_FlujoBasico(MantenimientoTienda.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertarTienda_FlujoBasico -->
        <test-method status="SKIP" signature="insertarTienda_FlujoAlternativo2()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoTienda@64616ca2]" name="insertarTienda_FlujoAlternativo2" duration-ms="0" started-at="2019-06-25T23:32:15Z" depends-on-methods="pe.com.MDRO.test.system.selenium.testcase.MantenimientoTienda.insertarTienda_FlujoBasico" finished-at="2019-06-25T23:32:15Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MantenimientoTienda.insertarTienda_FlujoAlternativo2()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoTienda@64616ca2] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MantenimientoTienda.insertarTienda_FlujoAlternativo2()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoTienda@64616ca2] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertarTienda_FlujoAlternativo2 -->
        <test-method status="SKIP" signature="insertarTienda_FlujoAlternativo()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoTienda@64616ca2]" name="insertarTienda_FlujoAlternativo" duration-ms="0" started-at="2019-06-25T23:32:15Z" depends-on-methods="pe.com.MDRO.test.system.selenium.testcase.MantenimientoTienda.insertarTienda_FlujoBasico" finished-at="2019-06-25T23:32:15Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MantenimientoTienda.insertarTienda_FlujoAlternativo()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoTienda@64616ca2] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MantenimientoTienda.insertarTienda_FlujoAlternativo()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoTienda@64616ca2] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertarTienda_FlujoAlternativo -->
      </class> <!-- pe.com.MDRO.test.system.selenium.testcase.MantenimientoTienda -->
      <class name="pe.com.MDRO.test.system.selenium.testcase.MantenimientoCategoria">
        <test-method status="PASS" signature="insertarCategoria_FlujoBasico()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoCategoria@5f2050f6]" name="insertarCategoria_FlujoBasico" duration-ms="4781" started-at="2019-06-25T23:31:28Z" finished-at="2019-06-25T23:31:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertarCategoria_FlujoBasico -->
        <test-method status="FAIL" signature="insertarCategoria_FlujoAlternativo()[pri:0, instance:pe.com.MDRO.test.system.selenium.testcase.MantenimientoCategoria@5f2050f6]" name="insertarCategoria_FlujoAlternativo" duration-ms="2249" started-at="2019-06-25T23:31:33Z" depends-on-methods="pe.com.MDRO.test.system.selenium.testcase.MantenimientoCategoria.insertarCategoria_FlujoBasico" finished-at="2019-06-25T23:31:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Descripcion: Error de validación: se necesita un valor.] but found [Descripcion: Validation Error: Value is required.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Descripcion: Error de validación: se necesita un valor.] but found [Descripcion: Validation Error: Value is required.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pe.com.MDRO.test.system.selenium.testcase.MantenimientoCategoria.insertarCategoria_FlujoAlternativo(MantenimientoCategoria.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertarCategoria_FlujoAlternativo -->
      </class> <!-- pe.com.MDRO.test.system.selenium.testcase.MantenimientoCategoria -->
    </test> <!-- MantenimientoCategoriaTest -->
  </suite> <!-- VisorTestSuite -->
</testng-results>
